### ISSUE TITLE
CLI commands which used to work now give "Route does not exist" errors

### ISSUE THREAD

**Issue by jwflicker** [IBM/ibm-generative-ai-node-sdk#105]
CLI commands i used to build an IDz Generative AI plugin cease to work.
For examples see: https://github.ibm.com/jflicke/Generative-AI-for-IBM-Developer-for-Z/issues/2

Even command: 
genai generate config --reset
Route does not exist

Are there some recommended settings to aid in debugging?

Installed CLI using 'sudo' and -g on Apple M1 Max
Built an Eclipse plugin that used the node js that was installed

Unsure if relevant:
Later updated node and npm to newer version
re-installed CLI again using 'sudo' and -g on Apple M1 Max

Other users of my plugin report the same issue:
https://github.ibm.com/jflicke/Generative-AI-for-IBM-Developer-for-Z/issues/2

**Comment by jwflicker** [comment]
It appears the API route has changed, but the Cli does not accept a valid route:
https://bam.res.ibm.com/docs/api-reference#versioning

For example, the latesat valid route is:
https://bam-api.res.ibm.com/v2/path?version=2024-04-15

But the CLI or API does not seem to work with that value
```
jflicke@Jeremys-MacBook-Pro ~ % genai config
Endpoint (https://bam-api.res.ibm.com/v2/path): https://bam-api.res.ibm.com/v2/path?version=2024-04-15
API Key (pak-...): 

jflicke@Jeremys-MacBook-Pro ~ % genai generate config --reset
Invalid version, accepted format is YYYY-MM-DD
```

**Comment by jwflicker** [comment]
https://github.com/IBM/ibm-generative-ai-cli/issues/40

**Comment by ibmliqi** [comment]
The same error happened on Windows as well.

**Comment by David-Kristek** [comment]
Hi @jwflicker, 
the error you are getting - `Invalid version, accepted format is YYYY-MM-DD` is caused by an incorrect Endpoint in your configuration.  The endpoint should only be  `https://bam-api.res.ibm.com` - the version is handled by the CLI.

**Comment by pilartomas** [comment]
Hello @jwflicker, please make sure you're using CLI v2.

I am guessing you're still running on v1 since you have the `genai generate config --reset` command in it. The CLI v1 uses SDK v1 which calls `/v1` REST API endpoints that no longer exist, hence the `Route does not exist` error.

@David-Kristek correctly pointed you that you should only set the endpoint, date versioning is handled by the SDK (and therefore CLI).
