### ISSUE TITLE
Is there an example on Custom Agent?

### ISSUE THREAD

**Issue by playground** [IBM/ibm-generative-ai-node-sdk#106]
Hi,

Is there a Custom Agent example similar to this one [Custom LLM Agent](https://js.langchain.com/v0.1/docs/modules/agents/how_to/custom_llm_agent/ )?

**Comment by Tomas2D** [comment]
Hey, not really. However, you can follow the LangChain tutorial mentioned above, but with one difference: you will import LLM from this library instead of from LangChain.
