### ISSUE TITLE
Types don't work in ESM + node16

### ISSUE THREAD

**Issue by benasher44** [IBM/ibm-generative-ai-node-sdk#112]
See https://arethetypeswrong.github.io/?p=%40ibm-generative-ai%2Fnode-sdk%403.2.0

When importing the types in ESM via promptfoo, you get:

> The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@ibm-generative-ai/node-sdk")' call instead.

**Comment by Tomas2D** [comment]
Thanks for the report.

Fixed in v3.2.1

**Comment by benasher44** [comment]
Amazing thank you!
