### ISSUE TITLE
Missing prompt_id field for generate method

### ISSUE THREAD

**Issue by hamedizadpanah-ibm** [IBM/ibm-generative-ai-node-sdk#22]
The latest APIs allow the generate method to be involved by passing a "prompt_id" field to allow the use of prompt templates
API Documents: /docs/api-reference#generate_prompt

Please add this to the existing package so that generate method can have:
`
client.generate({
  input: newInput,
  prompt_id: "<<prompt id>>"
});
`

**Comment by Tomas2D** [comment]
Thanks for the report.

Released in 1.2.0 🚀
