### ISSUE TITLE
Production WatsonX endpoints

### ISSUE THREAD

**Issue by garrettrowe** [IBM/ibm-generative-ai-node-sdk#37]
Hi, the library seems to be pinned to the Tech Preview of WatsonX.  The production WatsonX paths are quite different. Is there a near term plan to allow for the production paths to be used?

**Comment by Tomas2D** [comment]
Hello Garret,

Maybe you are looking for https://github.com/IBM/watsonxdata-node-sdk.

**Comment by garrettrowe** [comment]
That is a repo for the WatsonX.data - the lakehouse product.

WatsonX.ai (generativeAI / LLM's) have different production paths than the tech preview, which are hardcoded in this library.

Eg: Tech preview vs production endpoints & paths:
Tech Preview: 	https://workbench-api.res.ibm.com/v1/generate
Prod:  			https://us-south.ml.cloud.ibm.com/ml/v1-beta/generation/text?version=2023-05-29

**Comment by Tomas2D** [comment]
I see; we had an internal discussion about it, and we would like to collaborate on compatibility with WatsonX API. 

Let's keep this issue open, and I will post an update here.

**Comment by chasemcdo** [comment]
Hey Team! Our team is also interested in a package for use with production WatsonX credentials. Is there any update on this?

**Comment by Tomas2D** [comment]
Hey, we will discuss the SDKs on Monday; if you need to work with WatsonX urgently, you can use their endpoint for the text generation via Rest API.

**Comment by Tomas2D** [comment]
There is no plan to align NodeJS SDK, only the Python SDK. I will reopen this thread if anything changes.

**Comment by faileon** [comment]
> Thanks Tomas! Yah, we’re presently using the Rest API directly, but we’re interested in a cleaner approach for potential integration with LangChain. Excited to see what comes of this :)

Im sorry to resurect this thread but I am becoming desperate. Where can I find the REST API documentation so I can use the `generate` functions for chat models in my nodeJS app? I've been looking for hours and I can't find anything. The only thing close to it is the Watson ML API https://cloud.ibm.com/apidocs/machine-learning

**Comment by chasemcdo** [comment]
> > Thanks Tomas! Yah, we’re presently using the Rest API directly, but we’re interested in a cleaner approach for potential integration with LangChain. Excited to see what comes of this :)
> 
> Im sorry to resurect this thread but I am becoming desperate. Where can I find the REST API documentation so I can use the `generate`, `generate_text` and `generate_text_stream` functions for chat models in my nodeJS app, similar to the mentioned python package? I've been looking for hours and I can't find anything. The only thing close to it is the Watson ML API https://cloud.ibm.com/apidocs/machine-learning

Hey faileon,
I haven't found much in terms of comprehensive documentation for interacting with the prompt lab model API directly. Though the docs you linked are helpful for auth and generation IAM tokens.

The best form of _documentation_ I have found for using the prompt lab model API is the pop up code block within the prompt lab 

<img width="1512" alt="image" src="https://github.com/IBM/ibm-generative-ai-node-sdk/assets/74692158/914fa134-01a2-48a1-8102-b49e00ef56ea">

Using these calls you can interact with the api to generate predictions using WatsonX.ai models.
If this is what you are after I have recently added an integration to LangChain for just this which will likely be deployed by the end of this week.

**Comment by chasemcdo** [comment]
@faileon for the more complex actions it may be possible to extract the URLs from the [Python SDK](https://ibm.github.io/watson-machine-learning-sdk/_modules/ibm_watson_machine_learning/foundation_models/model.html#Model).

Looks like the endpoints are visible as `text` or `text_stream` etc

**Comment by faileon** [comment]
> @faileon for the more complex actions it may be possible to extract the URLs from the [Python SDK](https://ibm.github.io/watson-machine-learning-sdk/_modules/ibm_watson_machine_learning/foundation_models/model.html#Model).
> 
> Looks like the endpoints are visible as `text` or `text_stream` etc

Thanks, yup seems that reverse engineering python SDK is the only "sane" way. I also found an open api specs somewhere here - https://github.com/watson-developer-cloud/assistant-toolkit/blob/master/integrations/extensions/starter-kits/language-model-watsonx/watsonx-openapi.json

This is super bad developer experience so far...

**Comment by ericsaleh** [comment]
@faileon we are hoping to publish the API specs soon. The frustration and gap this creates in the meantime is totally understandable: it's a top priority for the watsonx team to close this
