### ISSUE TITLE
readme doesnt state how to select the model

### ISSUE THREAD

**Issue by aviv1ron1** [IBM/ibm-generative-ai-node-sdk#44]
when I query I get an error 'Default model is not defined.'
but the documentation doesnt state how to select the model or any other parameters

**Comment by Tomas2D** [comment]
Hey @aviv1ron1,

The examples can be seen in `examples` or `tests` directory.

```javascript
const data = await client.generate({
    model_id: 'bigscience/bloom',
    input: 'Hello, World',
    parameters: {
        decoding_method: 'greedy',      
    }
});
```
