### ISSUE TITLE
Unable to use anything in the SDK due to #private methods

### ISSUE THREAD

**Issue by saevarb** [IBM/ibm-generative-ai-node-sdk#61]
Hi.

I'm currently trying to use this SDK to build an integration to WatsonX.ai for [Flowise](https://github.com/FlowiseAI/Flowise) and am running into issues.

In particular, I'm trying to add WatsonX as a "Chat model" in Flowise, and all of these chat models are essentially just built on top of langchain abstractions. See [this example](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chatmodels/ChatLocalAI/ChatLocalAI.ts). As far as I can tell, I think this should mean that I should basically just be able to reuse this SDK's `GenAIModel` and/or `GenAIChatModel`. Unfortunately, I cannot use the SDK in any way because it appears that private(#-private) methods are being called from derived classes in some weird way that results in errors like this:

```ts
        this.client = new GenAIChatModel({
            modelId: 'meta-llama/llama-2-70b-chat',
            parameters: {},
            configuration: {
                apiKey: data.iamApiKey,
                endpoint: data.instanceUrl
            },
            rolesMapping: {
                human: {
                    stopSequence: '<human>:'
                },
                system: {
                    stopSequence: '<bot>:'
                }
            }
        })
// ...
        const res = await this.client.call(messages)
```
```
TypeError: Cannot read private member #rolesMapping from an object whose class did not declare it
     at [..]/Flowise/node_modules/@ibm-generative-ai/node-sdk/dist/langchain/index.cjs:1576:25
```

Errors of this type happen regardless of how I use either `GenAIModel` or `GenAIChatModel`. As a hacky temporary fix, I tried just changing a lot of #private methods to non-private, as I encountered these errors, but every single use of #private methods or variables resulted in errors - I had to simply remove every hashtag in the code for it to even run at all.

I *think* this may have something to do with bundling or something to that effect, but I simply don't have the time to create a minimal reproducible example.

**Comment by Tomas2D** [comment]
Hello, thanks for the report. 

I was not able to reproduce the problem with the latest version of SDK and Langchain and Node.js version 18.17.1. 
Please ensure you are running the newest versions and then let me know.
